
package cn.gyyx.action.service.client.account;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Account", targetNamespace = "http://asktao.gbits.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Account {


    /**
     * 
     * @param arguments
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "Register")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Register", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.Register")
    @ResponseWrapper(localName = "RegisterResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.RegisterResponse")
    public ProcessResult register(
        @WebParam(name = "arguments", targetNamespace = "")
        String arguments);

    /**
     * 
     * @param duration
     * @param reason
     * @param account
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "Suspend")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Suspend", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.Suspend")
    @ResponseWrapper(localName = "SuspendResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.SuspendResponse")
    public ProcessResult suspend(
        @WebParam(name = "account", targetNamespace = "")
        String account,
        @WebParam(name = "duration", targetNamespace = "")
        int duration,
        @WebParam(name = "reason", targetNamespace = "")
        String reason);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetVersion")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetVersion", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.GetVersion")
    @ResponseWrapper(localName = "GetVersionResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.GetVersionResponse")
    public String getVersion();

    /**
     * 
     * @param newPassword
     * @param account
     * @param oldPassword
     * @param protect
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "UpdatePassword")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "UpdatePassword", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.UpdatePassword")
    @ResponseWrapper(localName = "UpdatePasswordResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.UpdatePasswordResponse")
    public ProcessResult updatePassword(
        @WebParam(name = "account", targetNamespace = "")
        String account,
        @WebParam(name = "newPassword", targetNamespace = "")
        String newPassword,
        @WebParam(name = "oldPassword", targetNamespace = "")
        String oldPassword,
        @WebParam(name = "protect", targetNamespace = "")
        String protect);

    /**
     * 
     * @param checkValue
     * @param account
     * @param silverGoldRatio
     * @param transactionID
     * @param numberOfCoins
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "Charge")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Charge", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.Charge")
    @ResponseWrapper(localName = "ChargeResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.ChargeResponse")
    public ProcessResult charge(
        @WebParam(name = "TransactionID", targetNamespace = "")
        String transactionID,
        @WebParam(name = "account", targetNamespace = "")
        String account,
        @WebParam(name = "numberOfCoins", targetNamespace = "")
        int numberOfCoins,
        @WebParam(name = "silverGoldRatio", targetNamespace = "")
        int silverGoldRatio,
        @WebParam(name = "checkValue", targetNamespace = "")
        String checkValue);

    /**
     * 
     * @param checkValue
     * @param account
     * @param silverGoldRatio
     * @param chargeType
     * @param transactionID
     * @param numberOfCoins
     * @param serverCaption
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "ChargeEx")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ChargeEx", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.ChargeEx")
    @ResponseWrapper(localName = "ChargeExResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.ChargeExResponse")
    public ProcessResult chargeEx(
        @WebParam(name = "transactionID", targetNamespace = "")
        String transactionID,
        @WebParam(name = "account", targetNamespace = "")
        String account,
        @WebParam(name = "chargeType", targetNamespace = "")
        int chargeType,
        @WebParam(name = "numberOfCoins", targetNamespace = "")
        int numberOfCoins,
        @WebParam(name = "silverGoldRatio", targetNamespace = "")
        int silverGoldRatio,
        @WebParam(name = "checkValue", targetNamespace = "")
        String checkValue,
        @WebParam(name = "serverCaption", targetNamespace = "")
        String serverCaption);

    /**
     * 
     * @param checkValue
     * @param silverCoins
     * @param account
     * @param chargeType
     * @param transactionID
     * @param goldCoins
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "CheckTransCharge")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CheckTransCharge", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.CheckTransCharge")
    @ResponseWrapper(localName = "CheckTransChargeResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.CheckTransChargeResponse")
    public ProcessResult checkTransCharge(
        @WebParam(name = "TransactionID", targetNamespace = "")
        String transactionID,
        @WebParam(name = "Account", targetNamespace = "")
        String account,
        @WebParam(name = "ChargeType", targetNamespace = "")
        int chargeType,
        @WebParam(name = "GoldCoins", targetNamespace = "")
        int goldCoins,
        @WebParam(name = "SilverCoins", targetNamespace = "")
        int silverCoins,
        @WebParam(name = "CheckValue", targetNamespace = "")
        String checkValue);

    /**
     * 
     * @param checkValue
     * @param silverCoins
     * @param account
     * @param chargeType
     * @param transactionID
     * @param serverCaption
     * @param goldCoins
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "CheckTransChargeEx")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CheckTransChargeEx", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.CheckTransChargeEx")
    @ResponseWrapper(localName = "CheckTransChargeExResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.CheckTransChargeExResponse")
    public ProcessResult checkTransChargeEx(
        @WebParam(name = "transactionID", targetNamespace = "")
        String transactionID,
        @WebParam(name = "account", targetNamespace = "")
        String account,
        @WebParam(name = "chargeType", targetNamespace = "")
        int chargeType,
        @WebParam(name = "goldCoins", targetNamespace = "")
        int goldCoins,
        @WebParam(name = "silverCoins", targetNamespace = "")
        int silverCoins,
        @WebParam(name = "checkValue", targetNamespace = "")
        String checkValue,
        @WebParam(name = "serverCaption", targetNamespace = "")
        String serverCaption);

    /**
     * 
     * @param arguments
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "RegisterEx")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RegisterEx", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.RegisterEx")
    @ResponseWrapper(localName = "RegisterExResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.RegisterExResponse")
    public ProcessResult registerEx(
        @WebParam(name = "arguments", targetNamespace = "")
        String arguments);

    /**
     * 
     * @param account
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "LockAccount")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "LockAccount", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.LockAccount")
    @ResponseWrapper(localName = "LockAccountResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.LockAccountResponse")
    public ProcessResult lockAccount(
        @WebParam(name = "account", targetNamespace = "")
        String account);

    /**
     * 
     * @param account
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "UnlockAccount")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "UnlockAccount", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.UnlockAccount")
    @ResponseWrapper(localName = "UnlockAccountResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.UnlockAccountResponse")
    public ProcessResult unlockAccount(
        @WebParam(name = "account", targetNamespace = "")
        String account);

    /**
     * 
     * @param arg0
     * @return
     *     returns cn.gyyx.action.service.client.account.QueryAccountLockStatusResult
     */
    @WebMethod(operationName = "QueryAccountLockStatus")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "QueryAccountLockStatus", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.QueryAccountLockStatus")
    @ResponseWrapper(localName = "QueryAccountLockStatusResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.QueryAccountLockStatusResponse")
    public QueryAccountLockStatusResult queryAccountLockStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param account
     * @return
     *     returns cn.gyyx.action.service.client.account.QueryResult
     */
    @WebMethod(operationName = "QuerySpentCoins")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "QuerySpentCoins", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.QuerySpentCoins")
    @ResponseWrapper(localName = "QuerySpentCoinsResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.QuerySpentCoinsResponse")
    public QueryResult querySpentCoins(
        @WebParam(name = "account", targetNamespace = "")
        String account);

    /**
     * 
     * @param account
     * @return
     *     returns cn.gyyx.action.service.client.account.QueryResult
     */
    @WebMethod(operationName = "QueryRemainingCoins")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "QueryRemainingCoins", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.QueryRemainingCoins")
    @ResponseWrapper(localName = "QueryRemainingCoinsResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.QueryRemainingCoinsResponse")
    public QueryResult queryRemainingCoins(
        @WebParam(name = "account", targetNamespace = "")
        String account);

    /**
     * 
     * @param maxNumOfReturnedRecords
     * @param startDate
     * @param startIndex
     * @param account
     * @param endDate
     * @return
     *     returns cn.gyyx.action.service.client.account.QueryTransactionHistoryResult
     */
    @WebMethod(operationName = "QueryTransactionHistory")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "QueryTransactionHistory", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.QueryTransactionHistory")
    @ResponseWrapper(localName = "QueryTransactionHistoryResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.QueryTransactionHistoryResponse")
    public QueryTransactionHistoryResult queryTransactionHistory(
        @WebParam(name = "account", targetNamespace = "")
        String account,
        @WebParam(name = "startIndex", targetNamespace = "")
        int startIndex,
        @WebParam(name = "maxNumOfReturnedRecords", targetNamespace = "")
        int maxNumOfReturnedRecords,
        @WebParam(name = "startDate", targetNamespace = "")
        XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param characterIDs
     * @param checkValue
     * @param accounts
     * @param memo
     * @param encourageType
     * @param expiredTime
     * @param dists
     * @return
     *     returns java.util.List<cn.gyyx.action.service.client.account.ProcessResult>
     */
    @WebMethod(operationName = "BatchGivePresents")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "BatchGivePresents", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.BatchGivePresents")
    @ResponseWrapper(localName = "BatchGivePresentsResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.BatchGivePresentsResponse")
    public List<ProcessResult> batchGivePresents(
        @WebParam(name = "accounts", targetNamespace = "")
        List<String> accounts,
        @WebParam(name = "characterIDs", targetNamespace = "")
        List<String> characterIDs,
        @WebParam(name = "dists", targetNamespace = "")
        List<String> dists,
        @WebParam(name = "encourageType", targetNamespace = "")
        String encourageType,
        @WebParam(name = "expiredTime", targetNamespace = "")
        String expiredTime,
        @WebParam(name = "memo", targetNamespace = "")
        String memo,
        @WebParam(name = "checkValue", targetNamespace = "")
        String checkValue);

    /**
     * 
     * @param checkValue
     * @param memo
     * @param encourageType
     * @param expiredTime
     * @param account
     * @param characterID
     * @param dist
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "GivePresents")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GivePresents", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.GivePresents")
    @ResponseWrapper(localName = "GivePresentsResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.GivePresentsResponse")
    public ProcessResult givePresents(
        @WebParam(name = "account", targetNamespace = "")
        String account,
        @WebParam(name = "dist", targetNamespace = "")
        String dist,
        @WebParam(name = "characterID", targetNamespace = "")
        String characterID,
        @WebParam(name = "encourageType", targetNamespace = "")
        String encourageType,
        @WebParam(name = "expiredTime", targetNamespace = "")
        String expiredTime,
        @WebParam(name = "memo", targetNamespace = "")
        String memo,
        @WebParam(name = "checkValue", targetNamespace = "")
        String checkValue);

    /**
     * 
     * @param account
     * @param password
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "SetUpdateCoinPassword")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SetUpdateCoinPassword", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.SetUpdateCoinPassword")
    @ResponseWrapper(localName = "SetUpdateCoinPasswordResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.SetUpdateCoinPasswordResponse")
    public ProcessResult setUpdateCoinPassword(
        @WebParam(name = "account", targetNamespace = "")
        String account,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param account
     * @return
     *     returns cn.gyyx.action.service.client.account.CoinPasswordStateResult
     */
    @WebMethod(operationName = "GetCoinPasswordState")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetCoinPasswordState", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.GetCoinPasswordState")
    @ResponseWrapper(localName = "GetCoinPasswordStateResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.GetCoinPasswordStateResponse")
    public CoinPasswordStateResult getCoinPasswordState(
        @WebParam(name = "account", targetNamespace = "")
        String account);

    /**
     * 
     * @param account
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "CancelRemoveCoinPassword")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CancelRemoveCoinPassword", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.CancelRemoveCoinPassword")
    @ResponseWrapper(localName = "CancelRemoveCoinPasswordResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.CancelRemoveCoinPasswordResponse")
    public ProcessResult cancelRemoveCoinPassword(
        @WebParam(name = "account", targetNamespace = "")
        String account);

    /**
     * 
     * @param account
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "RemoveCoinPassword")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RemoveCoinPassword", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.RemoveCoinPassword")
    @ResponseWrapper(localName = "RemoveCoinPasswordResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.RemoveCoinPasswordResponse")
    public ProcessResult removeCoinPassword(
        @WebParam(name = "account", targetNamespace = "")
        String account);

    /**
     * 
     * @param account
     * @return
     *     returns cn.gyyx.action.service.client.account.GetProtectCardStateResult
     */
    @WebMethod(operationName = "GetProtectCardState")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetProtectCardState", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.GetProtectCardState")
    @ResponseWrapper(localName = "GetProtectCardStateResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.GetProtectCardStateResponse")
    public GetProtectCardStateResult getProtectCardState(
        @WebParam(name = "account", targetNamespace = "")
        String account);

    /**
     * 
     * @param account
     * @param protectCardValue
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "SetUpdateProtectCard")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SetUpdateProtectCard", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.SetUpdateProtectCard")
    @ResponseWrapper(localName = "SetUpdateProtectCardResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.SetUpdateProtectCardResponse")
    public ProcessResult setUpdateProtectCard(
        @WebParam(name = "account", targetNamespace = "")
        String account,
        @WebParam(name = "protectCardValue", targetNamespace = "")
        String protectCardValue);

    /**
     * 
     * @param duration
     * @param reason
     * @param account
     * @param protectCardValue
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "LostProtectCard")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "LostProtectCard", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.LostProtectCard")
    @ResponseWrapper(localName = "LostProtectCardResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.LostProtectCardResponse")
    public ProcessResult lostProtectCard(
        @WebParam(name = "account", targetNamespace = "")
        String account,
        @WebParam(name = "protectCardValue", targetNamespace = "")
        String protectCardValue,
        @WebParam(name = "duration", targetNamespace = "")
        int duration,
        @WebParam(name = "reason", targetNamespace = "")
        String reason);

    /**
     * 
     * @param account
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "CancelProtectCard")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CancelProtectCard", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.CancelProtectCard")
    @ResponseWrapper(localName = "CancelProtectCardResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.CancelProtectCardResponse")
    public ProcessResult cancelProtectCard(
        @WebParam(name = "account", targetNamespace = "")
        String account);

    /**
     * 
     * @param account
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "CancelLostProtectCard")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CancelLostProtectCard", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.CancelLostProtectCard")
    @ResponseWrapper(localName = "CancelLostProtectCardResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.CancelLostProtectCardResponse")
    public ProcessResult cancelLostProtectCard(
        @WebParam(name = "account", targetNamespace = "")
        String account);

    /**
     * 
     * @param account
     * @return
     *     returns cn.gyyx.action.service.client.account.IsAdultResult
     */
    @WebMethod(operationName = "IsAdult")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "IsAdult", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.IsAdult")
    @ResponseWrapper(localName = "IsAdultResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.IsAdultResponse")
    public IsAdultResult isAdult(
        @WebParam(name = "account", targetNamespace = "")
        String account);

    /**
     * 
     * @param account
     * @param adult
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "SetAdult")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SetAdult", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.SetAdult")
    @ResponseWrapper(localName = "SetAdultResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.SetAdultResponse")
    public ProcessResult setAdult(
        @WebParam(name = "account", targetNamespace = "")
        String account,
        @WebParam(name = "adult", targetNamespace = "")
        int adult);

    /**
     * 
     * @param account
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "SetVipSms")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SetVipSms", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.SetVipSms")
    @ResponseWrapper(localName = "SetVipSmsResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.SetVipSmsResponse")
    public ProcessResult setVipSms(
        @WebParam(name = "account", targetNamespace = "")
        String account);

    /**
     * 
     * @param oper
     * @param account
     * @param bindTime
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "SetUpdatePhoneAuth")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SetUpdatePhoneAuth", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.SetUpdatePhoneAuth")
    @ResponseWrapper(localName = "SetUpdatePhoneAuthResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.SetUpdatePhoneAuthResponse")
    public ProcessResult setUpdatePhoneAuth(
        @WebParam(name = "account", targetNamespace = "")
        String account,
        @WebParam(name = "bindTime", targetNamespace = "")
        String bindTime,
        @WebParam(name = "oper", targetNamespace = "")
        String oper);

    /**
     * 
     * @param oper
     * @param account
     * @param alipayAccount
     * @param bindTime
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "SetUpdateAlipayAccount")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SetUpdateAlipayAccount", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.SetUpdateAlipayAccount")
    @ResponseWrapper(localName = "SetUpdateAlipayAccountResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.SetUpdateAlipayAccountResponse")
    public ProcessResult setUpdateAlipayAccount(
        @WebParam(name = "account", targetNamespace = "")
        String account,
        @WebParam(name = "alipayAccount", targetNamespace = "")
        String alipayAccount,
        @WebParam(name = "bindTime", targetNamespace = "")
        String bindTime,
        @WebParam(name = "oper", targetNamespace = "")
        String oper);

    /**
     * 
     * @param securityType
     * @param account
     * @param options
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "AutomaticLock")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AutomaticLock", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.AutomaticLock")
    @ResponseWrapper(localName = "AutomaticLockResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.AutomaticLockResponse")
    public ProcessResult automaticLock(
        @WebParam(name = "account", targetNamespace = "")
        String account,
        @WebParam(name = "securityType", targetNamespace = "")
        int securityType,
        @WebParam(name = "options", targetNamespace = "")
        int options);

    /**
     * 
     * @param duration
     * @param securityType
     * @param account
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "SetLockTimer")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SetLockTimer", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.SetLockTimer")
    @ResponseWrapper(localName = "SetLockTimerResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.SetLockTimerResponse")
    public ProcessResult setLockTimer(
        @WebParam(name = "account", targetNamespace = "")
        String account,
        @WebParam(name = "securityType", targetNamespace = "")
        int securityType,
        @WebParam(name = "duration", targetNamespace = "")
        int duration);

    /**
     * 
     * @param account
     * @return
     *     returns cn.gyyx.action.service.client.account.GetLockStateResult
     */
    @WebMethod(operationName = "GetLockState")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetLockState", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.GetLockState")
    @ResponseWrapper(localName = "GetLockStateResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.GetLockStateResponse")
    public GetLockStateResult getLockState(
        @WebParam(name = "account", targetNamespace = "")
        String account);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "SetAccountSettingAutoLock")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SetAccountSettingAutoLock", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.SetAccountSettingAutoLock")
    @ResponseWrapper(localName = "SetAccountSettingAutoLockResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.SetAccountSettingAutoLockResponse")
    public ProcessResult setAccountSettingAutoLock(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns cn.gyyx.action.service.client.account.GetAccountSettingAutoLockStateResult
     */
    @WebMethod(operationName = "GetAccountSettingAutoLockState")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetAccountSettingAutoLockState", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.GetAccountSettingAutoLockState")
    @ResponseWrapper(localName = "GetAccountSettingAutoLockStateResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.GetAccountSettingAutoLockStateResponse")
    public GetAccountSettingAutoLockStateResult getAccountSettingAutoLockState(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param checkValue
     * @param numberOfSilverCoins
     * @param account
     * @param giftReasonDesc
     * @param transactionID
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "GiftSilverCoins")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GiftSilverCoins", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.GiftSilverCoins")
    @ResponseWrapper(localName = "GiftSilverCoinsResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.GiftSilverCoinsResponse")
    public ProcessResult giftSilverCoins(
        @WebParam(name = "transactionID", targetNamespace = "")
        String transactionID,
        @WebParam(name = "account", targetNamespace = "")
        String account,
        @WebParam(name = "numberOfSilverCoins", targetNamespace = "")
        int numberOfSilverCoins,
        @WebParam(name = "giftReasonDesc", targetNamespace = "")
        String giftReasonDesc,
        @WebParam(name = "checkValue", targetNamespace = "")
        String checkValue);

    /**
     * 
     * @param checkValue
     * @param numberOfSilverCoins
     * @param account
     * @param giftReasonDesc
     * @param chargeType
     * @param transactionID
     * @param serverCaption
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "GiftSilverCoinsEx")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GiftSilverCoinsEx", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.GiftSilverCoinsEx")
    @ResponseWrapper(localName = "GiftSilverCoinsExResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.GiftSilverCoinsExResponse")
    public ProcessResult giftSilverCoinsEx(
        @WebParam(name = "transactionID", targetNamespace = "")
        String transactionID,
        @WebParam(name = "account", targetNamespace = "")
        String account,
        @WebParam(name = "chargeType", targetNamespace = "")
        int chargeType,
        @WebParam(name = "numberOfSilverCoins", targetNamespace = "")
        int numberOfSilverCoins,
        @WebParam(name = "giftReasonDesc", targetNamespace = "")
        String giftReasonDesc,
        @WebParam(name = "checkValue", targetNamespace = "")
        String checkValue,
        @WebParam(name = "serverCaption", targetNamespace = "")
        String serverCaption);

    /**
     * 
     * @param checkValue
     * @param silverCoins
     * @param giftType
     * @param giftReason
     * @param account
     * @param transactionID
     * @param serverCaption
     * @param goldCoins
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "GiftCoins")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GiftCoins", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.GiftCoins")
    @ResponseWrapper(localName = "GiftCoinsResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.GiftCoinsResponse")
    public ProcessResult giftCoins(
        @WebParam(name = "transactionID", targetNamespace = "")
        String transactionID,
        @WebParam(name = "account", targetNamespace = "")
        String account,
        @WebParam(name = "giftType", targetNamespace = "")
        int giftType,
        @WebParam(name = "goldCoins", targetNamespace = "")
        int goldCoins,
        @WebParam(name = "silverCoins", targetNamespace = "")
        int silverCoins,
        @WebParam(name = "giftReason", targetNamespace = "")
        String giftReason,
        @WebParam(name = "serverCaption", targetNamespace = "")
        String serverCaption,
        @WebParam(name = "checkValue", targetNamespace = "")
        String checkValue);

    /**
     * 
     * @param account
     * @return
     *     returns cn.gyyx.action.service.client.account.QueryAccountBlockHistoryResult
     */
    @WebMethod(operationName = "QueryAccountBlockHistory")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "QueryAccountBlockHistory", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.QueryAccountBlockHistory")
    @ResponseWrapper(localName = "QueryAccountBlockHistoryResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.QueryAccountBlockHistoryResponse")
    public QueryAccountBlockHistoryResult queryAccountBlockHistory(
        @WebParam(name = "account", targetNamespace = "")
        String account);

    /**
     * 
     * @param account
     * @return
     *     returns cn.gyyx.action.service.client.account.QueryAccountBlockReasonResult
     */
    @WebMethod(operationName = "QueryAccountBlockReason")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "QueryAccountBlockReason", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.QueryAccountBlockReason")
    @ResponseWrapper(localName = "QueryAccountBlockReasonResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.QueryAccountBlockReasonResponse")
    public QueryAccountBlockReasonResult queryAccountBlockReason(
        @WebParam(name = "account", targetNamespace = "")
        String account);

    /**
     * 
     * @param account
     * @return
     *     returns cn.gyyx.action.service.client.account.GetProtectCardStateResult
     */
    @WebMethod(operationName = "GetMatrixStateForStoragePwd")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetMatrixStateForStoragePwd", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.GetMatrixStateForStoragePwd")
    @ResponseWrapper(localName = "GetMatrixStateForStoragePwdResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.GetMatrixStateForStoragePwdResponse")
    public GetProtectCardStateResult getMatrixStateForStoragePwd(
        @WebParam(name = "account", targetNamespace = "")
        String account);

    /**
     * 
     * @param account
     * @param protectCardValue
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "SetUpdateMatrixForStoragePwd")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SetUpdateMatrixForStoragePwd", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.SetUpdateMatrixForStoragePwd")
    @ResponseWrapper(localName = "SetUpdateMatrixForStoragePwdResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.SetUpdateMatrixForStoragePwdResponse")
    public ProcessResult setUpdateMatrixForStoragePwd(
        @WebParam(name = "account", targetNamespace = "")
        String account,
        @WebParam(name = "protectCardValue", targetNamespace = "")
        String protectCardValue);

    /**
     * 
     * @param account
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "CancelMatrixForStoragePwd")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CancelMatrixForStoragePwd", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.CancelMatrixForStoragePwd")
    @ResponseWrapper(localName = "CancelMatrixForStoragePwdResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.CancelMatrixForStoragePwdResponse")
    public ProcessResult cancelMatrixForStoragePwd(
        @WebParam(name = "account", targetNamespace = "")
        String account);

    /**
     * 
     * @param account
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "ImmediatelyCancelMatrixForStoragePwd")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ImmediatelyCancelMatrixForStoragePwd", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.ImmediatelyCancelMatrixForStoragePwd")
    @ResponseWrapper(localName = "ImmediatelyCancelMatrixForStoragePwdResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.ImmediatelyCancelMatrixForStoragePwdResponse")
    public ProcessResult immediatelyCancelMatrixForStoragePwd(
        @WebParam(name = "account", targetNamespace = "")
        String account);

    /**
     * 
     * @param account
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "GetLocalEncryptState")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetLocalEncryptState", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.GetLocalEncryptState")
    @ResponseWrapper(localName = "GetLocalEncryptStateResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.GetLocalEncryptStateResponse")
    public ProcessResult getLocalEncryptState(
        @WebParam(name = "account", targetNamespace = "")
        String account);

    /**
     * 
     * @param account
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "RemoveLocalEncrypt")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RemoveLocalEncrypt", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.RemoveLocalEncrypt")
    @ResponseWrapper(localName = "RemoveLocalEncryptResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.RemoveLocalEncryptResponse")
    public ProcessResult removeLocalEncrypt(
        @WebParam(name = "account", targetNamespace = "")
        String account);

    /**
     * 
     * @param transactionID
     * @return
     *     returns cn.gyyx.action.service.client.account.QueryIntResult
     */
    @WebMethod(operationName = "QueryTransactionID")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "QueryTransactionID", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.QueryTransactionID")
    @ResponseWrapper(localName = "QueryTransactionIDResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.QueryTransactionIDResponse")
    public QueryIntResult queryTransactionID(
        @WebParam(name = "TransactionID", targetNamespace = "")
        String transactionID);

    /**
     * 
     * @param protectValue
     * @param md5Checksum
     * @param securityType
     * @param account
     * @param bindTime
     * @return
     *     returns cn.gyyx.action.service.client.account.ProcessResult
     */
    @WebMethod(operationName = "SyncProtectInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SyncProtectInfo", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.SyncProtectInfo")
    @ResponseWrapper(localName = "SyncProtectInfoResponse", targetNamespace = "http://asktao.gbits.com/", className = "cn.gyyx.action.service.client.account.SyncProtectInfoResponse")
    public ProcessResult syncProtectInfo(
        @WebParam(name = "account", targetNamespace = "")
        String account,
        @WebParam(name = "securityType", targetNamespace = "")
        int securityType,
        @WebParam(name = "bindTime", targetNamespace = "")
        String bindTime,
        @WebParam(name = "protectValue", targetNamespace = "")
        String protectValue,
        @WebParam(name = "md5Checksum", targetNamespace = "")
        String md5Checksum);

}
