/**
 * -------------------------------------------------------------------------
 * @版权所有：北京光宇在线科技有限责任公司
 * @项目名称：action-dao
 * @作者：guoyonggang
 * @联系方式：guoyonggang@gyyx.cn
 * @创建时间：2017年2月27日
 * @版本号：1.0
 * @本类主要用途描述：  
 *-------------------------------------------------------------------------
 */
package cn.gyyx.action.dao.wechatcharge;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.gyyx.action.beans.wechatcharge.WechatChargeBean;
import cn.gyyx.action.beans.wechatcharge.WechatChargePaginationBean;

/**
  * <p>
  *   微信兑换活动数据操作Mapper
  * </p>
  *  
  * @author guoyonggang
  * @since 0.0.1
 */
public interface IWechatChargeMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table wechat_charge_tb
     *
     * @mbggenerated Mon Feb 27 15:45:16 CST 2017
     */
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table wechat_charge_tb
     *
     * @mbggenerated Mon Feb 27 15:45:16 CST 2017
     */
    int insert(WechatChargeBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table wechat_charge_tb
     *
     * @mbggenerated Mon Feb 27 15:45:16 CST 2017
     */
    int insertSelective(WechatChargeBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table wechat_charge_tb
     *
     * @mbggenerated Mon Feb 27 15:45:16 CST 2017
     */
    WechatChargeBean selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table wechat_charge_tb
     *
     * @mbggenerated Mon Feb 27 15:45:16 CST 2017
     */
    int updateByPrimaryKeySelective(WechatChargeBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table wechat_charge_tb
     *
     * @mbggenerated Mon Feb 27 15:45:16 CST 2017
     */
    int updateByPrimaryKey(WechatChargeBean record);

    /**
     * <p>
     * 分页查询结果
     * </p>
     *
     * @action guoyonggang 2017年2月28日 下午1:13:16 描述
     *
     * @param queryCondition
     * @return List<WechatChargeBean>
     */
    List<WechatChargeBean> queryWechatChargeList(
            WechatChargePaginationBean queryCondition);


    /**
     * <p>
     * 分页查询总条数
     * </p>
     *
     * @action guoyonggang 2017年2月28日 下午1:13:16 描述
     *
     * @param queryCondition
     * @return List<WechatChargeBean>
     */
    int queryWechatChargeCount(WechatChargePaginationBean queryCondition);

    /**
     * <p>
     * 查询结果用于导出数据
     * </p>
     *
     * @action guoyonggang 2017年2月28日 下午1:13:16 描述
     *
     * @param queryCondition
     * @return List<WechatChargeBean>
     */
    List<WechatChargeBean> queryWechatChargeListForExport(@Param("strWhere")String strWhere);

    /**
     * <p>
     * 根据openId查询兑换记录
     * </p>
     *
     * @action guoyonggang 2017年2月28日 下午1:13:16 描述
     *
     * @param openId
     * @return List<WechatChargeBean>
     */
    List<WechatChargeBean> queryWechatChargeListByOpenId(@Param("openId")String openId);

    /**
     * <p>
     * 根据兑换码查询兑换记录
     * </p>
     *
     * @action guoyonggang 2017年2月28日 下午1:13:16 描述
     *
     * @param chargeCode
     * @return List<WechatChargeBean>
     */
    WechatChargeBean queryWechatChargeByChargeCode(@Param("chargeCode")String chargeCode);
}