package cn.mahjong.dao;

import cn.mahjong.beans.AccountBindChangePhoneLog;

public interface AccountBindChangePhoneLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_bind_change_phone_log
     *
     * @mbggenerated Wed May 31 15:13:08 CST 2017
     */
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_bind_change_phone_log
     *
     * @mbggenerated Wed May 31 15:13:08 CST 2017
     */
    int insert(AccountBindChangePhoneLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_bind_change_phone_log
     *
     * @mbggenerated Wed May 31 15:13:08 CST 2017
     */
    int insertSelective(AccountBindChangePhoneLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_bind_change_phone_log
     *
     * @mbggenerated Wed May 31 15:13:08 CST 2017
     */
    AccountBindChangePhoneLog selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_bind_change_phone_log
     *
     * @mbggenerated Wed May 31 15:13:08 CST 2017
     */
    int updateByPrimaryKeySelective(AccountBindChangePhoneLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_bind_change_phone_log
     *
     * @mbggenerated Wed May 31 15:13:08 CST 2017
     */
    int updateByPrimaryKey(AccountBindChangePhoneLog record);
}