package cn.mahjong.dao;

import cn.mahjong.beans.AccountLoginLog;

public interface AccountLoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_login_log
     *
     * @mbggenerated Tue May 23 14:51:02 CST 2017
     */
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_login_log
     *
     * @mbggenerated Tue May 23 14:51:02 CST 2017
     */
    int insert(AccountLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_login_log
     *
     * @mbggenerated Tue May 23 14:51:02 CST 2017
     */
    int insertSelective(AccountLoginLog record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_login_log
     *
     * @mbggenerated Tue May 23 14:51:02 CST 2017
     */
    AccountLoginLog selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_login_log
     *
     * @mbggenerated Tue May 23 14:51:02 CST 2017
     */
    int updateByPrimaryKeySelective(AccountLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_login_log
     *
     * @mbggenerated Tue May 23 14:51:02 CST 2017
     */
    int updateByPrimaryKey(AccountLoginLog record);
}