package cn.mahjong.dao;

import cn.mahjong.beans.AccountFindChangePwdLog;

public interface AccountFindChangePwdLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_find_change_pwd_log
     *
     * @mbggenerated Wed May 24 16:02:20 CST 2017
     */
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_find_change_pwd_log
     *
     * @mbggenerated Wed May 24 16:02:20 CST 2017
     */
    int insert(AccountFindChangePwdLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_find_change_pwd_log
     *
     * @mbggenerated Wed May 24 16:02:20 CST 2017
     */
    int insertSelective(AccountFindChangePwdLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_find_change_pwd_log
     *
     * @mbggenerated Wed May 24 16:02:20 CST 2017
     */
    AccountFindChangePwdLog selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_find_change_pwd_log
     *
     * @mbggenerated Wed May 24 16:02:20 CST 2017
     */
    int updateByPrimaryKeySelective(AccountFindChangePwdLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_find_change_pwd_log
     *
     * @mbggenerated Wed May 24 16:02:20 CST 2017
     */
    int updateByPrimaryKey(AccountFindChangePwdLog record);
}