package cn.mahjong.dao;

import cn.mahjong.beans.BlockLog;

public interface BlockLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_log
     *
     * @mbggenerated Tue May 23 14:48:09 CST 2017
     */
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_log
     *
     * @mbggenerated Tue May 23 14:48:09 CST 2017
     */
    int insert(BlockLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_log
     *
     * @mbggenerated Tue May 23 14:48:09 CST 2017
     */
    int insertSelective(BlockLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_log
     *
     * @mbggenerated Tue May 23 14:48:09 CST 2017
     */
    BlockLog selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_log
     *
     * @mbggenerated Tue May 23 14:48:09 CST 2017
     */
    int updateByPrimaryKeySelective(BlockLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table block_log
     *
     * @mbggenerated Tue May 23 14:48:09 CST 2017
     */
    int updateByPrimaryKey(BlockLog record);
}