package cn.mahjong.dao;

import cn.mahjong.beans.GameBean;

public interface GameBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tb
     *
     * @mbggenerated Thu Jun 01 14:30:52 CST 2017
     */
    int insert(GameBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table game_tb
     *
     * @mbggenerated Thu Jun 01 14:30:52 CST 2017
     */
    int insertSelective(GameBean record);
}