package cn.mahjong.dao;

import cn.mahjong.beans.GameNewRoomBean;

public interface GameNewRoomBeanMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table game_new_room_tb
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table game_new_room_tb
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    int insert(GameNewRoomBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table game_new_room_tb
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    int insertSelective(GameNewRoomBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table game_new_room_tb
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    GameNewRoomBean selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table game_new_room_tb
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    int updateByPrimaryKeySelective(GameNewRoomBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table game_new_room_tb
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    int updateByPrimaryKey(GameNewRoomBean record);
}