package cn.mahjong.dao;

import cn.mahjong.beans.GameLoginBean;

public interface GameLoginBeanMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table game_login_tb
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table game_login_tb
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    int insert(GameLoginBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table game_login_tb
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    int insertSelective(GameLoginBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table game_login_tb
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    GameLoginBean selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table game_login_tb
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    int updateByPrimaryKeySelective(GameLoginBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table game_login_tb
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    int updateByPrimaryKey(GameLoginBean record);
}