package cn.mahjong.dao;

import cn.mahjong.beans.GameRegBean;

public interface GameRegBeanMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table game_reg_tb
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table game_reg_tb
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    int insert(GameRegBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table game_reg_tb
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    int insertSelective(GameRegBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table game_reg_tb
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    GameRegBean selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table game_reg_tb
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    int updateByPrimaryKeySelective(GameRegBean record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table game_reg_tb
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    int updateByPrimaryKey(GameRegBean record);
}