package cn.mahjong.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.mahjong.beans.UserBean;

public interface UserBeanMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tb
     *
     * @mbggenerated Tue May 23 14:48:09 CST 2017
     */
    int insert(UserBean record);

    void insertInfo(UserBean user);

    void insertHeadInfo(UserBean user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tb
     *
     * @mbggenerated Tue May 23 14:48:09 CST 2017
     */
    UserBean selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tb
     *
     * @mbggenerated Tue May 23 14:48:09 CST 2017
     */
    int updateByPrimaryKeySelective(UserBean record);
    int updateInfoByPrimaryKeySelective(UserBean record);
    int updateHeadInfoByPrimaryKeySelective(UserBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tb
     *
     * @mbggenerated Tue May 23 14:48:09 CST 2017
     */
    int updateByPrimaryKey(UserBean record);
    
    UserBean selectByAccount(String account);

    List<UserBean> selectSubByUserId(@Param("userId")Integer userId,
                                    @Param("status")String status,
                                    @Param("offset")Integer offset, 
                                    @Param("rows")Integer rows);
    
    int updatePwdByPrimaryKey(@Param("code")Integer code,@Param("password")String password);

    void block(int userId);

    void unblock(int userId);
}