package cn.mahjong.beans;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table account_login_log
 *
 * @mbggenerated do_not_delete_during_merge Tue May 23 14:51:02 CST 2017
 */
public class AccountLoginLog {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_login_log.code
     *
     * @mbggenerated Tue May 23 14:51:02 CST 2017
     */
    private Integer code;

    /**
     * Database Column Remarks:
     *   用户主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_login_log.user_id
     *
     * @mbggenerated Tue May 23 14:51:02 CST 2017
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   登录IP
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_login_log.login_ip
     *
     * @mbggenerated Tue May 23 14:51:02 CST 2017
     */
    private Integer loginIp;

    /**
     * Database Column Remarks:
     *   登录时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_login_log.login_time
     *
     * @mbggenerated Tue May 23 14:51:02 CST 2017
     */
    private Date loginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_login_log.code
     *
     * @return the value of account_login_log.code
     *
     * @mbggenerated Tue May 23 14:51:02 CST 2017
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_login_log.code
     *
     * @param code the value for account_login_log.code
     *
     * @mbggenerated Tue May 23 14:51:02 CST 2017
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_login_log.user_id
     *
     * @return the value of account_login_log.user_id
     *
     * @mbggenerated Tue May 23 14:51:02 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_login_log.user_id
     *
     * @param userId the value for account_login_log.user_id
     *
     * @mbggenerated Tue May 23 14:51:02 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_login_log.login_ip
     *
     * @return the value of account_login_log.login_ip
     *
     * @mbggenerated Tue May 23 14:51:02 CST 2017
     */
    public Integer getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_login_log.login_ip
     *
     * @param loginIp the value for account_login_log.login_ip
     *
     * @mbggenerated Tue May 23 14:51:02 CST 2017
     */
    public void setLoginIp(Integer loginIp) {
        this.loginIp = loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_login_log.login_time
     *
     * @return the value of account_login_log.login_time
     *
     * @mbggenerated Tue May 23 14:51:02 CST 2017
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_login_log.login_time
     *
     * @param loginTime the value for account_login_log.login_time
     *
     * @mbggenerated Tue May 23 14:51:02 CST 2017
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }
}