package cn.mahjong.beans;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table account_find_change_pwd_log
 *
 * @mbggenerated do_not_delete_during_merge Wed May 24 16:02:20 CST 2017
 */
public class AccountFindChangePwdLog {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_find_change_pwd_log.code
     *
     * @mbggenerated Wed May 24 16:02:20 CST 2017
     */
    private Integer code;

    /**
     * Database Column Remarks:
     *   用户主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_find_change_pwd_log.user_id
     *
     * @mbggenerated Wed May 24 16:02:20 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_find_change_pwd_log.ip
     *
     * @mbggenerated Wed May 24 16:02:20 CST 2017
     */
    private Integer ip;

    /**
     * Database Column Remarks:
     *   操作类型（找回密码，修改密码）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_find_change_pwd_log.type
     *
     * @mbggenerated Wed May 24 16:02:20 CST 2017
     */
    private String type;

    /**
     * Database Column Remarks:
     *   操作者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_find_change_pwd_log.operator
     *
     * @mbggenerated Wed May 24 16:02:20 CST 2017
     */
    private String operator;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_find_change_pwd_log.create_time
     *
     * @mbggenerated Wed May 24 16:02:20 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_find_change_pwd_log.code
     *
     * @return the value of account_find_change_pwd_log.code
     *
     * @mbggenerated Wed May 24 16:02:20 CST 2017
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_find_change_pwd_log.code
     *
     * @param code the value for account_find_change_pwd_log.code
     *
     * @mbggenerated Wed May 24 16:02:20 CST 2017
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_find_change_pwd_log.user_id
     *
     * @return the value of account_find_change_pwd_log.user_id
     *
     * @mbggenerated Wed May 24 16:02:20 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_find_change_pwd_log.user_id
     *
     * @param userId the value for account_find_change_pwd_log.user_id
     *
     * @mbggenerated Wed May 24 16:02:20 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_find_change_pwd_log.ip
     *
     * @return the value of account_find_change_pwd_log.ip
     *
     * @mbggenerated Wed May 24 16:02:20 CST 2017
     */
    public Integer getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_find_change_pwd_log.ip
     *
     * @param ip the value for account_find_change_pwd_log.ip
     *
     * @mbggenerated Wed May 24 16:02:20 CST 2017
     */
    public void setIp(Integer ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_find_change_pwd_log.type
     *
     * @return the value of account_find_change_pwd_log.type
     *
     * @mbggenerated Wed May 24 16:02:20 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_find_change_pwd_log.type
     *
     * @param type the value for account_find_change_pwd_log.type
     *
     * @mbggenerated Wed May 24 16:02:20 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_find_change_pwd_log.operator
     *
     * @return the value of account_find_change_pwd_log.operator
     *
     * @mbggenerated Wed May 24 16:02:20 CST 2017
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_find_change_pwd_log.operator
     *
     * @param operator the value for account_find_change_pwd_log.operator
     *
     * @mbggenerated Wed May 24 16:02:20 CST 2017
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_find_change_pwd_log.create_time
     *
     * @return the value of account_find_change_pwd_log.create_time
     *
     * @mbggenerated Wed May 24 16:02:20 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_find_change_pwd_log.create_time
     *
     * @param createTime the value for account_find_change_pwd_log.create_time
     *
     * @mbggenerated Wed May 24 16:02:20 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}