package cn.mahjong.beans;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table block_log
 *
 * @mbggenerated do_not_delete_during_merge Tue May 23 14:48:09 CST 2017
 */
public class BlockLog {

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column block_log.code
   *
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  private Integer code;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column block_log.create_time
   *
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  private Date createTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column block_log.user_id
   *
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  private Integer userId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column block_log.operator
   *
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  private Integer operator;

  private String type;
  private String reason;

  public BlockLog() {

  }

  public BlockLog(String type, Integer userId, Integer operator, String reason, Date createTime) {
    this.type = type;
    this.createTime = createTime;
    this.userId = userId;
    this.operator = operator;
    this.reason = reason;
  }

  @Override
  public String toString() {
    return "BlockLog{" +
        "code=" + code +
        ", createTime=" + createTime +
        ", userId=" + userId +
        ", operator=" + operator +
        ", type='" + type + '\'' +
        ", reason='" + reason + '\'' +
        '}';
  }

  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column block_log.code
   *
   * @return the value of block_log.code
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  public Integer getCode() {
    return code;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column block_log.code
   *
   * @param code the value for block_log.code
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  public void setCode(Integer code) {
    this.code = code;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column block_log.create_time
   *
   * @return the value of block_log.create_time
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column block_log.create_time
   *
   * @param createTime the value for block_log.create_time
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column block_log.user_id
   *
   * @return the value of block_log.user_id
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  public Integer getUserId() {
    return userId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column block_log.user_id
   *
   * @param userId the value for block_log.user_id
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column block_log.operator
   *
   * @return the value of block_log.operator
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  public Integer getOperator() {
    return operator;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column block_log.operator
   *
   * @param operator the value for block_log.operator
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  public void setOperator(Integer operator) {
    this.operator = operator;
  }
}