package cn.mahjong.beans;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table game_new_room_tb
 *
 * @mbggenerated do_not_delete_during_merge Thu Jun 01 14:30:52 CST 2017
 */
public class GameNewRoomBean {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column game_new_room_tb.code
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    private Integer code;
    /**
     * Database Column Remarks: 游戏标识 This field was generated by MyBatis Generator. This field corresponds to the database column game_new_room_tb.game_id
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    private Integer gameId;
    /**
     * Database Column Remarks: 游戏内用户标识 This field was generated by MyBatis Generator. This field corresponds to the database column game_new_room_tb.user_id
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    private Integer userId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column game_new_room_tb.ip
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    private String ip;
    /**
     * Database Column Remarks: 创建房间时间 This field was generated by MyBatis Generator. This field corresponds to the database column game_new_room_tb.new_room_time
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    private Date newRoomTime;
    /**
     * Database Column Remarks: 创建时间 This field was generated by MyBatis Generator. This field corresponds to the database column game_new_room_tb.create_time
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column game_new_room_tb.code
     * @return  the value of game_new_room_tb.code
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column game_new_room_tb.code
     * @param code  the value for game_new_room_tb.code
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column game_new_room_tb.game_id
     * @return  the value of game_new_room_tb.game_id
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    public Integer getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column game_new_room_tb.game_id
     * @param gameId  the value for game_new_room_tb.game_id
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    public void setGameId(Integer gameId) {
        this.gameId = gameId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column game_new_room_tb.user_id
     * @return  the value of game_new_room_tb.user_id
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column game_new_room_tb.user_id
     * @param userId  the value for game_new_room_tb.user_id
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column game_new_room_tb.ip
     * @return  the value of game_new_room_tb.ip
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column game_new_room_tb.ip
     * @param ip  the value for game_new_room_tb.ip
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column game_new_room_tb.new_room_time
     * @return  the value of game_new_room_tb.new_room_time
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    public Date getNewRoomTime() {
        return newRoomTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column game_new_room_tb.new_room_time
     * @param newRoomTime  the value for game_new_room_tb.new_room_time
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    public void setNewRoomTime(Date newRoomTime) {
        this.newRoomTime = newRoomTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column game_new_room_tb.create_time
     * @return  the value of game_new_room_tb.create_time
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column game_new_room_tb.create_time
     * @param createTime  the value for game_new_room_tb.create_time
     * @mbggenerated  Thu Jun 01 14:56:10 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}