package cn.mahjong.beans;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table game_tb
 *
 * @mbggenerated do_not_delete_during_merge Thu Jun 01 14:30:52 CST 2017
 */
public class GameBean {
    /**
     * Database Column Remarks:
     *   游戏ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_tb.game_id
     *
     * @mbggenerated Thu Jun 01 14:30:52 CST 2017
     */
    private Integer gameId;

    /**
     * Database Column Remarks:
     *   游戏名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_tb.game_name
     *
     * @mbggenerated Thu Jun 01 14:30:52 CST 2017
     */
    private String gameName;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_tb.desc
     *
     * @mbggenerated Thu Jun 01 14:30:52 CST 2017
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_tb.game_id
     *
     * @return the value of game_tb.game_id
     *
     * @mbggenerated Thu Jun 01 14:30:52 CST 2017
     */
    public Integer getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_tb.game_id
     *
     * @param gameId the value for game_tb.game_id
     *
     * @mbggenerated Thu Jun 01 14:30:52 CST 2017
     */
    public void setGameId(Integer gameId) {
        this.gameId = gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_tb.game_name
     *
     * @return the value of game_tb.game_name
     *
     * @mbggenerated Thu Jun 01 14:30:52 CST 2017
     */
    public String getGameName() {
        return gameName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_tb.game_name
     *
     * @param gameName the value for game_tb.game_name
     *
     * @mbggenerated Thu Jun 01 14:30:52 CST 2017
     */
    public void setGameName(String gameName) {
        this.gameName = gameName == null ? null : gameName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_tb.desc
     *
     * @return the value of game_tb.desc
     *
     * @mbggenerated Thu Jun 01 14:30:52 CST 2017
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_tb.desc
     *
     * @param desc the value for game_tb.desc
     *
     * @mbggenerated Thu Jun 01 14:30:52 CST 2017
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }
}