package cn.mahjong.beans;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_tb
 *
 * @mbggenerated do_not_delete_during_merge Tue May 23 14:48:09 CST 2017
 */
public class UserBean {

  /**
   * Database Column Remarks:
   *
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_tb.code
   *
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  private Integer code;

  /**
   * Database Column Remarks:
   *
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_tb.account
   *
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  private String account;

  /**
   * Database Column Remarks:
   *
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_tb.password
   *
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  private String password;

  /**
   * Database Column Remarks:
   *
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_tb.salt
   *
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  private String salt;

  /**
   * Database Column Remarks:
   *
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_tb.phone
   *
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  private String phone;

  /**
   * 姓名/昵称（局头）
   */
  private String name;

  /**
   * Database Column Remarks:
   *
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_tb.role
   *
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  private String role;

  /**
   * 上级 ID
   */
  private int parentId;

  /**
   * Database Column Remarks:
   *
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_tb.status
   *
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  private String status;

  /**
   * Database Column Remarks:
   *
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_tb.create_time
   *
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  private Date createTime;

  /**
   * 卡点余额
   */
  private int cardInventory;
  /**
   * 赠送余额
   */
  private int cardGiftInventory;
  /**
   * 省
   */
  private String province;
  /**
   * 市
   */
  private String city;
  /**
   * 地址
   */
  private String address;
  /**
   * 游戏用户ID
   */
  private Integer gameUserId;
  
  /**
   * 游戏标识
   */
  private Integer gameId;


  /**
   * 微信号
   */
  private String wechatId;

  @Override
  public String toString() {
    return "UserBean{" +
        "code=" + code +
        ", account='" + account + '\'' +
        ", phone='" + phone + '\'' +
        ", name='" + name + '\'' +
        ", role='" + role + '\'' +
        ", parentId=" + parentId +
        ", status='" + status + '\'' +
        ", createTime=" + createTime +
        ", cardInventory=" + cardInventory +
        ", cardGiftInventory=" + cardGiftInventory +
        ", province='" + province + '\'' +
        ", city='" + city + '\'' +
        ", address='" + address + '\'' +
        ", gameUserId=" + gameUserId +
        ", wechatId='" + wechatId + '\'' +
        '}';
  }

  public int getCardGiftInventory() {
    return cardGiftInventory;
  }

  public void setCardGiftInventory(int cardGiftInventory) {
    this.cardGiftInventory = cardGiftInventory;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_tb.code
   *
   * @return the value of user_tb.code
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  public Integer getCode() {
    return code;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_tb.code
   *
   * @param code the value for user_tb.code
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  public void setCode(Integer code) {
    this.code = code;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_tb.account
   *
   * @return the value of user_tb.account
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  public String getAccount() {
    return account;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_tb.account
   *
   * @param account the value for user_tb.account
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  public void setAccount(String account) {
    this.account = account == null ? null : account.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_tb.password
   *
   * @return the value of user_tb.password
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  public String getPassword() {
    return password;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_tb.password
   *
   * @param password the value for user_tb.password
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  public void setPassword(String password) {
    this.password = password == null ? null : password.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_tb.salt
   *
   * @return the value of user_tb.salt
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  public String getSalt() {
    return salt;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_tb.salt
   *
   * @param salt the value for user_tb.salt
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  public void setSalt(String salt) {
    this.salt = salt == null ? null : salt.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_tb.phone
   *
   * @return the value of user_tb.phone
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  public String getPhone() {
    return phone;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_tb.phone
   *
   * @param phone the value for user_tb.phone
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  public void setPhone(String phone) {
    this.phone = phone == null ? null : phone.trim();
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_tb.role
   *
   * @return the value of user_tb.role
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  public String getRole() {
    return role;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_tb.role
   *
   * @param role the value for user_tb.role
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  public void setRole(String role) {
    this.role = role == null ? null : role.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_tb.status
   *
   * @return the value of user_tb.status
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  public String getStatus() {
    return status;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_tb.status
   *
   * @param status the value for user_tb.status
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  public void setStatus(String status) {
    this.status = status == null ? null : status.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_tb.create_time
   *
   * @return the value of user_tb.create_time
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column user_tb.create_time
   *
   * @param createTime the value for user_tb.create_time
   * @mbggenerated Tue May 23 14:48:09 CST 2017
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  public int getParentId() {
    return this.parentId;
  }

  public void setParentId(int parentId) {
    this.parentId = parentId;
  }

  public int getCardInventory() {
    return this.cardInventory;
  }

  public void setCardInventory(int inventory) {
    this.cardInventory = inventory;
  }

  public String getProvince() {
    return province;
  }

  public void setProvince(String province) {
    this.province = province;
  }

  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public Integer getGameUserId() {
    return gameUserId;
  }

  public void setGameUserId(Integer gameUserId) {
    this.gameUserId = gameUserId;
  }

  public String getWechatId() {
    return wechatId;
  }

  public void setWechatId(String wechatId) {
    this.wechatId = wechatId;
  }

  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public synchronized Integer getGameId() {
      return gameId;
  }
    
  public synchronized void setGameId(Integer gameId) {
      this.gameId = gameId;
  }
}