/**
  * -------------------------------------------------------------------------
  * (C) Copyright Gyyx Tec Corp. 1996-2017 - All Rights Reserved
  * @版权所有：北京光宇在线科技有限责任公司
  * @项目名称：action-wd11thyearscommentwall-oa
  * @作者：guoyonggang
  * @联系方式：guoyonggang@gyyx.cn
  * @创建时间：2017年3月13日 下午4:22:49
  * @版本号：0.0.1
  *-------------------------------------------------------------------------
  */
package cn.gyyx.action.oa.wd11thyearscommentwall.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import cn.gyyx.action.oa.wd11thyearscommentwall.beans.WdElevenCommentWallBean;

/**
  * <p>
  *   问道11周年留言墙数据库操作Mapper
  * </p>
  *  
  * @author guoyonggang
  * @since 0.0.1
  */
public interface IWdElevenCommentWallBeanMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wd_eleven_comment_wall_tb
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    int updateByPrimaryKeySelective(WdElevenCommentWallBean record);
    
    /**
      * <p>
      *    分页查询评论数据
      * </p>
      *
      * @action
      *    guoyonggang 2017年3月13日 下午4:35:55 描述
      *
      * @param pageIndex
      *         页码
      * @param pageSize
      *         每页记录数
      * @param forwardPage
      *         第一页到前一页总条数
      * @param strWhere
      *         查询条件
      * @return List<WdElevenCommentWallBean>
      *         评论集合
     */
    List<WdElevenCommentWallBean> queryElevenYearsCommentList(
            @Param("pageIndex") Integer pageIndex,
            @Param("pageSize") Integer pageSize,
            @Param("forwardPage") Integer forwardPage,
            @Param("strWhere") String strWhere);
    /**
     * 
      * <p>
      *    查询评论总数
      * </p>
      *
      * @action
      *    guoyonggang 2017年3月13日 下午4:37:12 描述
      *
      * @param strWhere
      *         查询条件
      * @return int
      *         总条数
     */
    int queryElevenYearsCommentCount(@Param("strWhere") String strWhere);
    
    /**
      * <p>
      *    获取评论墙统计数据
      * </p>
      *
      * @action
      *    guoyonggang 2017年3月13日 下午5:08:54 描述
      *
      * @param strWhere
      *         查询条件
      * @return List<Map<String,Object>>
      *         查询结果
     */
    List<Map<String,Object>> queryElevenYearsCommentStatistics(@Param("strWhere") String strWhere);

}
