/**
  * -------------------------------------------------------------------------
  * (C) Copyright Gyyx Tec Corp. 1996-2017 - All Rights Reserved
  * @版权所有：北京光宇在线科技有限责任公司
  * @项目名称：action-wd11thyearscommentwall-oa
  * @作者：guoyonggang
  * @联系方式：guoyonggang@gyyx.cn
  * @创建时间：2017年3月13日 下午4:12:21
  * @版本号：0.0.1
  *-------------------------------------------------------------------------
  */
package cn.gyyx.action.oa.wd11thyearscommentwall.beans;

import java.util.Date;

/**
  * <p>
  *   问道十一周年评论墙Bean
  * </p>
  *  
  * @author guoyonggang
  * @since 0.0.1
  */
public class WdElevenCommentWallBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_eleven_comment_wall_tb.code
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    private Integer code;
    
    private String codes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_eleven_comment_wall_tb.action_code
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    private Integer actionCode;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hd_config_tb.action_name
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    private String actionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_eleven_comment_wall_tb.nick_name
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_eleven_comment_wall_tb.message
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_eleven_comment_wall_tb.source_tag
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    private String sourceTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_eleven_comment_wall_tb.is_audit
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    private Integer isAudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_eleven_comment_wall_tb.auditor
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    private String auditor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_eleven_comment_wall_tb.create_time
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wd_eleven_comment_wall_tb.audit_time
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    private Date auditTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_eleven_comment_wall_tb.code
     *
     * @return the value of wd_eleven_comment_wall_tb.code
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_eleven_comment_wall_tb.code
     *
     * @param code the value for wd_eleven_comment_wall_tb.code
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    public void setCode(Integer code) {
        this.code = code;
    }
    
    

    /**
     * @return the codes
     */
    public String getCodes() {
        return codes;
    }

    /**
     * @param codes the codes to set
     */
    public void setCodes(String codes) {
        this.codes = codes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_eleven_comment_wall_tb.action_code
     *
     * @return the value of wd_eleven_comment_wall_tb.action_code
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    public Integer getActionCode() {
        return actionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_eleven_comment_wall_tb.action_code
     *
     * @param actionCode the value for wd_eleven_comment_wall_tb.action_code
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    public void setActionCode(Integer actionCode) {
        this.actionCode = actionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hd_config_tb.action_name
     *
     * @return the value of hd_config_tb.action_name
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    public String getActionName() {
        return actionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hd_config_tb.action_name
     *
     * @param nickName the value for hd_config_tb.action_name
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    public void setActionName(String actionName) {
        this.actionName = actionName == null ? null : actionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_eleven_comment_wall_tb.nick_name
     *
     * @return the value of wd_eleven_comment_wall_tb.nick_name
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_eleven_comment_wall_tb.nick_name
     *
     * @param nickName the value for wd_eleven_comment_wall_tb.nick_name
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_eleven_comment_wall_tb.message
     *
     * @return the value of wd_eleven_comment_wall_tb.message
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_eleven_comment_wall_tb.message
     *
     * @param message the value for wd_eleven_comment_wall_tb.message
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_eleven_comment_wall_tb.source_tag
     *
     * @return the value of wd_eleven_comment_wall_tb.source_tag
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    public String getSourceTag() {
        return sourceTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_eleven_comment_wall_tb.source_tag
     *
     * @param sourceTag the value for wd_eleven_comment_wall_tb.source_tag
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    public void setSourceTag(String sourceTag) {
        this.sourceTag = sourceTag == null ? null : sourceTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_eleven_comment_wall_tb.is_audit
     *
     * @return the value of wd_eleven_comment_wall_tb.is_audit
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    public Integer getIsAudit() {
        return isAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_eleven_comment_wall_tb.is_audit
     *
     * @param isAudit the value for wd_eleven_comment_wall_tb.is_audit
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    public void setIsAudit(Integer isAudit) {
        this.isAudit = isAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_eleven_comment_wall_tb.auditor
     *
     * @return the value of wd_eleven_comment_wall_tb.auditor
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    public String getAuditor() {
        return auditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_eleven_comment_wall_tb.auditor
     *
     * @param auditor the value for wd_eleven_comment_wall_tb.auditor
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    public void setAuditor(String auditor) {
        this.auditor = auditor == null ? null : auditor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_eleven_comment_wall_tb.create_time
     *
     * @return the value of wd_eleven_comment_wall_tb.create_time
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_eleven_comment_wall_tb.create_time
     *
     * @param createTime the value for wd_eleven_comment_wall_tb.create_time
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wd_eleven_comment_wall_tb.audit_time
     *
     * @return the value of wd_eleven_comment_wall_tb.audit_time
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wd_eleven_comment_wall_tb.audit_time
     *
     * @param auditTime the value for wd_eleven_comment_wall_tb.audit_time
     *
     * @mbggenerated Mon Mar 13 15:25:23 CST 2017
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "WdElevenCommentWallBean [code=" + code + ", actionCode="
                + actionCode + ", nickName=" + nickName + ", message=" + message
                + ", sourceTag=" + sourceTag + ", isAudit=" + isAudit
                + ", auditor=" + auditor + ", createTime=" + createTime
                + ", auditTime=" + auditTime + "]";
    }
    
}
