package cn.gyyx.action.beans.wdtravelentry;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator. This class corresponds to the
 * database table wd_travel_entry_user_bind_role_tb
 *
 * @mbggenerated do_not_delete_during_merge Tue Jul 05 10:52:11 CST 2016
 */
public class WdTravelEntryUserBind {
	/**
	 *
	 *
	 * This field corresponds to the database column
	 * wd_travel_entry_user_bind_role_tb.code
	 *
	 * @mbggenerated Tue Jul 05 10:52:11 CST 2016
	 */
	private Integer code;

	/**
	 *
	 *
	 * This field corresponds to the database column
	 * wd_travel_entry_user_bind_role_tb.user_id
	 *
	 * @mbggenerated Tue Jul 05 10:52:11 CST 2016
	 */
	private Integer userId;

	/**
	 *
	 *
	 * This field corresponds to the database column
	 * wd_travel_entry_user_bind_role_tb.account
	 *
	 * @mbggenerated Tue Jul 05 10:52:11 CST 2016
	 */
	private String account;

	/**
	 *
	 *
	 * This field corresponds to the database column
	 * wd_travel_entry_user_bind_role_tb.region
	 *
	 * @mbggenerated Tue Jul 05 10:52:11 CST 2016
	 */
	private String region;

	/**
	 *
	 *
	 * This field corresponds to the database column
	 * wd_travel_entry_user_bind_role_tb.server_name
	 *
	 * @mbggenerated Tue Jul 05 10:52:11 CST 2016
	 */
	private String serverName;

	/**
	 *
	 *
	 * This field corresponds to the database column
	 * wd_travel_entry_user_bind_role_tb.server_id
	 *
	 * @mbggenerated Tue Jul 05 10:52:11 CST 2016
	 */
	private Integer serverId;

	/**
	 *
	 *
	 * This field corresponds to the database column
	 * wd_travel_entry_user_bind_role_tb.role_name
	 *
	 * @mbggenerated Tue Jul 05 10:52:11 CST 2016
	 */
	private String roleName;

	/**
	 *
	 *
	 * This field corresponds to the database column
	 * wd_travel_entry_user_bind_role_tb.create_time
	 *
	 * @mbggenerated Tue Jul 05 10:52:11 CST 2016
	 */
	private Date createTime;

	
	
	/**
	 * 构造
	 */
	public WdTravelEntryUserBind() {
		super();
	}

	/**
	 * 韩餐构造方法
	 * @param code
	 * @param userId
	 * @param account
	 * @param region
	 * @param serverName
	 * @param serverId
	 * @param roleName
	 * @param createTime
	 */
	public WdTravelEntryUserBind(Integer userId, String account, String region, String serverName,
			Integer serverId, String roleName, Date createTime) {
		super();
		this.userId = userId;
		this.account = account;
		this.region = region;
		this.serverName = serverName;
		this.serverId = serverId;
		this.roleName = roleName;
		this.createTime = createTime;
	}

	/**
	 * 
	 * This method returns the value of the database column
	 * wd_travel_entry_user_bind_role_tb.code
	 *
	 * @return the value of wd_travel_entry_user_bind_role_tb.code
	 *
	 * @mbggenerated Tue Jul 05 10:52:11 CST 2016
	 */
	public Integer getCode() {
		return code;
	}

	/**
	 * 
	 * This method sets the value of the database column
	 * wd_travel_entry_user_bind_role_tb.code
	 *
	 * @param code
	 *            the value for wd_travel_entry_user_bind_role_tb.code
	 *
	 * @mbggenerated Tue Jul 05 10:52:11 CST 2016
	 */
	public void setCode(Integer code) {
		this.code = code;
	}

	/**
	 * 
	 * This method returns the value of the database column
	 * wd_travel_entry_user_bind_role_tb.user_id
	 *
	 * @return the value of wd_travel_entry_user_bind_role_tb.user_id
	 *
	 * @mbggenerated Tue Jul 05 10:52:11 CST 2016
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * 
	 * This method sets the value of the database column
	 * wd_travel_entry_user_bind_role_tb.user_id
	 *
	 * @param userId
	 *            the value for wd_travel_entry_user_bind_role_tb.user_id
	 *
	 * @mbggenerated Tue Jul 05 10:52:11 CST 2016
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * 
	 * This method returns the value of the database column
	 * wd_travel_entry_user_bind_role_tb.account
	 *
	 * @return the value of wd_travel_entry_user_bind_role_tb.account
	 *
	 * @mbggenerated Tue Jul 05 10:52:11 CST 2016
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * 
	 * This method sets the value of the database column
	 * wd_travel_entry_user_bind_role_tb.account
	 *
	 * @param account
	 *            the value for wd_travel_entry_user_bind_role_tb.account
	 *
	 * @mbggenerated Tue Jul 05 10:52:11 CST 2016
	 */
	public void setAccount(String account) {
		this.account = account == null ? null : account.trim();
	}

	/**
	 * 
	 * This method returns the value of the database column
	 * wd_travel_entry_user_bind_role_tb.region
	 *
	 * @return the value of wd_travel_entry_user_bind_role_tb.region
	 *
	 * @mbggenerated Tue Jul 05 10:52:11 CST 2016
	 */
	public String getRegion() {
		return region;
	}

	/**
	 * 
	 * This method sets the value of the database column
	 * wd_travel_entry_user_bind_role_tb.region
	 *
	 * @param region
	 *            the value for wd_travel_entry_user_bind_role_tb.region
	 *
	 * @mbggenerated Tue Jul 05 10:52:11 CST 2016
	 */
	public void setRegion(String region) {
		this.region = region == null ? null : region.trim();
	}

	/**
	 * 
	 * This method returns the value of the database column
	 * wd_travel_entry_user_bind_role_tb.server_name
	 *
	 * @return the value of wd_travel_entry_user_bind_role_tb.server_name
	 *
	 * @mbggenerated Tue Jul 05 10:52:11 CST 2016
	 */
	public String getServerName() {
		return serverName;
	}

	/**
	 * 
	 * This method sets the value of the database column
	 * wd_travel_entry_user_bind_role_tb.server_name
	 *
	 * @param serverName
	 *            the value for wd_travel_entry_user_bind_role_tb.server_name
	 *
	 * @mbggenerated Tue Jul 05 10:52:11 CST 2016
	 */
	public void setServerName(String serverName) {
		this.serverName = serverName == null ? null : serverName.trim();
	}

	/**
	 * 
	 * This method returns the value of the database column
	 * wd_travel_entry_user_bind_role_tb.server_id
	 *
	 * @return the value of wd_travel_entry_user_bind_role_tb.server_id
	 *
	 * @mbggenerated Tue Jul 05 10:52:11 CST 2016
	 */
	public Integer getServerId() {
		return serverId;
	}

	/**
	 * 
	 * This method sets the value of the database column
	 * wd_travel_entry_user_bind_role_tb.server_id
	 *
	 * @param serverId
	 *            the value for wd_travel_entry_user_bind_role_tb.server_id
	 *
	 * @mbggenerated Tue Jul 05 10:52:11 CST 2016
	 */
	public void setServerId(Integer serverId) {
		this.serverId = serverId;
	}

	/**
	 * 
	 * This method returns the value of the database column
	 * wd_travel_entry_user_bind_role_tb.role_name
	 *
	 * @return the value of wd_travel_entry_user_bind_role_tb.role_name
	 *
	 * @mbggenerated Tue Jul 05 10:52:11 CST 2016
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * 
	 * This method sets the value of the database column
	 * wd_travel_entry_user_bind_role_tb.role_name
	 *
	 * @param roleName
	 *            the value for wd_travel_entry_user_bind_role_tb.role_name
	 *
	 * @mbggenerated Tue Jul 05 10:52:11 CST 2016
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName == null ? null : roleName.trim();
	}

	/**
	 * 
	 * This method returns the value of the database column
	 * wd_travel_entry_user_bind_role_tb.create_time
	 *
	 * @return the value of wd_travel_entry_user_bind_role_tb.create_time
	 *
	 * @mbggenerated Tue Jul 05 10:52:11 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * 
	 * This method sets the value of the database column
	 * wd_travel_entry_user_bind_role_tb.create_time
	 *
	 * @param createTime
	 *            the value for wd_travel_entry_user_bind_role_tb.create_time
	 *
	 * @mbggenerated Tue Jul 05 10:52:11 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Override
	public String toString() {
		return "WdTravelEntryUserBind [code=" + code + ", userId=" + userId + ", account=" + account + ", region="
				+ region + ", serverName=" + serverName + ", serverId=" + serverId + ", roleName=" + roleName
				+ ", createTime=" + createTime + "]";
	}

}